services:
  - type: web
    name: lili-watt-analyseur
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y poppler-utils
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
